### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dragxgaming** [nathanfarlow/SymbolicDerivative#8]
I open the program and it says "ERROR: SYNTAX"
and i can't figure out any way to fix it please help. TI84 + CE

**Comment by nathanfarlow** [comment]
You can run the program by pressing 2nd and 0. This brings you to the catalog. Scroll down to Asm( and press enter. Then press prgm and select the DERIV program and press enter. Press enter one more time to run it.

Alternatively, you can update your calculator to the latest firmware so that it can run assembly (and archived!) programs without needing the Asm( token.

**Comment by Dragxgaming** [comment]
Thank you, I was also missing the libraries I needed but I downloaded those. How do I update the calc? 
Sent from Yahoo Mail on Android 
 
  On Tue, Dec 5, 2017 at 10:32 PM, Nathan Farlow<notifications@github.com> wrote:   
You can run the program by pressing 2nd and 0. This brings you to the catalog. Scroll down to Asm( and press enter. Then press prgm and select the DERIV program and press enter. Press enter one more time to run it.

Alternatively, you can update your calculator to the latest firmware so that it can run assembly (and archived!) programs without needing the Asm( token.

**Comment by nathanfarlow** [comment]
You can get the OS and Ti Connect CE here: https://education.ti.com/en/software/update/download-84ce?soft=84-pl-ce,

You'll just send the os to the calculator through Ti Connect CE like any other app var
